INSERT INTO tb_user (phone, password, nick_name, icon)
SELECT
    CONCAT('13', FLOOR(RAND() * 900000000 + 100000000)) AS phone,
    MD5(FLOOR(RAND() * 1000000000)) AS password,
    CONCAT('user', FLOOR(RAND() * 100000 + 1000)) AS nick_name,
    CONCAT('https://example.com/icon/', FLOOR(RAND() * 1000)) AS icon
FROM
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
     SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1,
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
     SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2,
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
     SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t3;
